---
- name: Set up authentication
  when: sandbox_openshift_username | default(false)
  ansible.builtin.include_tasks: authentication.yaml

- name: Provision infrastructure
  when: ACTION == "provision"
  module_defaults:
    group/k8s:
      host: "{{ sandbox_openshift_api_url }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key | default(sandbox_openshift_api_key) }}"
      validate_certs: false
  block:
  - name: Include create_project.yaml
    when: sandbox_openshift_namespace is not defined
    ansible.builtin.include_tasks: create_project.yaml
  - name: Include create_networks.yaml
    ansible.builtin.include_tasks: create_networks.yaml
  - name: Include create_instances.yaml
    ansible.builtin.include_tasks: create_instances.yaml

- name: Destroy infrastructure
  when: ACTION == "destroy"
  module_defaults:
    group/k8s:
      host: "{{ sandbox_openshift_api_url }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key | default(sandbox_openshift_api_key) }}"
      validate_certs: false
  block:
  # Delete a project will delete the VMs, to discuss
  #- name: Include delete_instances.yaml
  #  ansible.builtin.include_tasks: delete_instances.yaml
  - name: Include delete_networks.yaml
    ansible.builtin.include_tasks: delete_networks.yaml
  - name: Include delete_project.yaml
    when: sandbox_openshift_namespace is not defined
    ansible.builtin.include_tasks: delete_project.yaml

- name: Manage instances
  when: ACTION in ["status", "start", "stop"]
  module_defaults:
    group/k8s:
      host: "{{ sandbox_openshift_api_url }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key | default(sandbox_openshift_api_key) }}"
      validate_certs: false
  block:
  - name: Include {{ ACTION }}_instances.yaml
    ansible.builtin.include_tasks: "{{ ACTION }}_instances.yaml"
