---
- name: Get a list of networks
  kubernetes.core.k8s_info:
    kind: NetworkAttachmentDefinition
    namespace: "{{ openshift_cnv_namespace }}"
  register: r_network_list
  until: r_network_list is success
  retries: "{{ openshift_cnv_retries }}"
  delay: "{{ openshift_cnv_delay }}"
  ignore_errors: true
