---
- name: Search for all running VMs
  kubernetes.core.k8s_info:
    api_version: kubevirt.io/v1
    kind: VirtualMachine
    namespace: "{{ openshift_cnv_namespace }}"
  register: r_openshift_cnv_instances
      
- name: Debug OpenShift CNV Instances fact
  ansible.builtin.debug:
    var: r_openshift_cnv_instances
    verbosity: 2

# Find the bastion
- name: Find the bastion in this batch of hosts
  when: '"bastions" in item.metadata.annotations.AnsibleGroup | default("")'
  ansible.builtin.set_fact:
    local_bastion: "{{ item.metadata.name }}"
  loop: "{{ r_openshift_cnv_instances.resources | list }}"
  ignore_errors: true

- name: Expose bastion externally
  when: local_bastion | default(false)
  kubernetes.core.k8s:
    host: "{{ sandbox_openshift_api_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key | default(sandbox_openshift_api_key) }}"
    validate_certs: false
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ local_bastion }}-ssh"
        namespace: "{{ openshift_cnv_namespace }}"
      spec:
        ports:
        - port: 22
          protocol: TCP
          targetPort: 22
        selector:
          vm.cnv.io/name: "{{ local_bastion }}"
        sessionAffinity: None
        type: NodePort
  register: r_expose_bastion
  until: r_expose_bastion is success
  retries: "{{ openshift_cnv_retries }}"
  delay: "{{ openshift_cnv_delay }}"

- name: Create inventory (add_host)
  when: item.metadata.annotations.managed | default(true) | bool
  ansible.builtin.add_host:
    name: "{{ item.metadata.name }}"
    shortname: "{{ item.metadata.name }}"
    ansible_user: "{{ remote_user }}"
    ansible_ssh_host: "{{ item.metadata.name }}"
    ssh_port: "{{ r_expose_bastion.result.spec.ports.0.nodePort | default(omit) }}"
    private_ip_address: "{{ item.metadata.name }}"
    public_ip_address: "{{ openshift_cnv_ssh_address }}"
    groups: "{{ item.metadata.annotations.AnsibleGroup | default(omit) }}"
    bastion: "{{ local_bastion | default('') }}"
    bastion_ssh_port: "{{ r_expose_bastion.result.spec.ports.0.nodePort | default(omit) }}"
    external_ip: "{{ item.metadata.annotations.external_ip | default(omit) }}"
    external_ports: "{{ item.metadata.annotations.external_ports | default(omit) }}"
    # Specify if the node is isolated, so won't connect to it
    isolated: "{{ item.metadata.annotations.isolated | default(false) }}"
  loop: "{{ r_openshift_cnv_instances.resources | list }}"
